// src/constants/MySkills.ts
import { SiRstudioide } from "react-icons/si";
export const MySkills = [
  {
    title: "Professional Skills",
    skills: [
      { name: "Data Cleaning", icon: null },
      { name: "Data Wrangling", icon: null },
      { name: "A/B Testing", icon: null },
      { name: "Critical Thinking", icon: null },
      { name: "Problem-Solving", icon: null },
      { name: "ETL", icon: null },
      { name: "Agile", icon: null },
      { name: "Scrum", icon: null },
      { name: "Microsoft Project", icon: null },
    ],
    index: 1,
  },
  {
    title: "Soft Skills",
    skills: [
      { name: "Communication Skills", icon: null },
      { name: "Presentation Skills", icon: null },
      { name: "Stakeholder Collaboration", icon: null },
      { name: "Adaptability", icon: null },
      { name: "Teamwork", icon: null },
    ],
    index: 2,
  },
  {
    title: "Technical Skills",
    skills: [
      { name: "Python", icon: "PythonOriginal" },
      { name: "R", icon: "SiRstudioide" },
      { name: "SQL", icon: "SqldeveloperOriginal" },
      { name: "RESTful API", icon: null },
      { name: "Apache Spark", icon: null },
      { name: "NLP", icon: null },
      { name: "NumPy", icon: null },
      { name: "BigQuery", icon: null },
      { name: "SSIS", icon: null },
      { name: "SAS", icon: null },
      { name: "SPSS", icon: null },
      { name: "Pandas", icon: null },
      { name: "Matplotlib", icon: null },
      { name: "SciPy", icon: null },
      { name: "ggplot2", icon: null },
      { name: "TensorFlow", icon: null },
      { name: "Keras", icon: null },
      { name: "Power BI (DAX)", icon: null },
      { name: "Tableau", icon: null },
      { name: "QlikView", icon: null },
      { name: "Snowflake", icon: null },
      { name: "SQL Server", icon: null },
      { name: "Oracle", icon: null },
      { name: "MySQL", icon: "MysqlOriginal" },
      { name: "Azure Databricks", icon: null },
      { name: "Informatica", icon: null },
      { name: "Azure", icon: null },
      { name: "AWS", icon: null },
      { name: "GCP", icon: null },
    ],
    index: 3,
  },
];
